//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wicked_Candles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CC()
        {
            this.Users = new HashSet<User>();
        }
    
        public int CCID { get; set; }
        public string CC_Name { get; set; }
        public Nullable<int> CC_Number { get; set; }
        public Nullable<System.DateTime> CC_Expiration { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<User> Users { get; set; }
    }
}
