//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wicked_Candles.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class User
    {
        public int UserID { get; set; }
        public string Name { get; set; }
        public Nullable<int> PhoneNumber { get; set; }
        public string Email_Address { get; set; }
        public string Street { get; set; }
        public string State { get; set; }
        public Nullable<int> Zip { get; set; }
        public string City { get; set; }
        public int CC_CCID { get; set; }
        public int Cart_CartID { get; set; }
        public int WishList_WishListID { get; set; }
        public int Transaction_TransactionID { get; set; }
    
        public virtual CC CC { get; set; }
    }
}
