-- MySQL Script generated by MySQL Workbench
-- Mon Jun 17 17:17:52 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Wicked_Candles
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Wicked_Candles
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Wicked_Candles` DEFAULT CHARACTER SET utf8 ;
USE `Wicked_Candles` ;

-- -----------------------------------------------------
-- Table `Wicked_Candles`.`CC`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wicked_Candles`.`CC` (
  `CCID` INT NOT NULL,
  `CC_Name` VARCHAR(45) NULL,
  `CC_Number` INT NULL,
  `CC_Expiration` DATE NULL,
  PRIMARY KEY (`CCID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wicked_Candles`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wicked_Candles`.`Product` (
  `ProductID` INT NOT NULL,
  `ProductName` VARCHAR(100) NOT NULL,
  `ProductDescription` VARCHAR(100) NOT NULL,
  `ProductImages` BLOB(64) NULL,
  `ProductPrice` DECIMAL(100) NOT NULL,
  PRIMARY KEY (`ProductID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wicked_Candles`.`Cart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wicked_Candles`.`Cart` (
  `CartID` INT NOT NULL,
  `Product_ProductID` INT NOT NULL,
  `ProductName` VARCHAR(45) NOT NULL,
  `ProductImage` BLOB(64) NOT NULL,
  `ProductPrice` DECIMAL(100) NOT NULL,
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`CartID`, `Product_ProductID`),
  INDEX `fk_Cart_Product1_idx` (`Product_ProductID` ASC),
  CONSTRAINT `fk_Cart_Product1`
    FOREIGN KEY (`Product_ProductID`)
    REFERENCES `Wicked_Candles`.`Product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wicked_Candles`.`WishList`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wicked_Candles`.`WishList` (
  `WishListID` INT NOT NULL,
  `Product_ProductID` INT NOT NULL,
  `ProductName` VARCHAR(100) NOT NULL,
  `ProductImage` BLOB(64) NOT NULL,
  `ProductPrice` DECIMAL(100) NOT NULL,
  PRIMARY KEY (`WishListID`, `Product_ProductID`),
  INDEX `fk_WishList_Product1_idx` (`Product_ProductID` ASC),
  CONSTRAINT `fk_WishList_Product1`
    FOREIGN KEY (`Product_ProductID`)
    REFERENCES `Wicked_Candles`.`Product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wicked_Candles`.`Transaction`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wicked_Candles`.`Transaction` (
  `TransactionID` INT NOT NULL,
  `Product_ProductID` INT NOT NULL,
  `ProductName` VARCHAR(45) NOT NULL,
  `ProductPrice` DECIMAL(100) NOT NULL,
  `Quantity` INT NOT NULL,
  PRIMARY KEY (`TransactionID`, `Product_ProductID`),
  INDEX `fk_Transaction_Product1_idx` (`Product_ProductID` ASC),
  CONSTRAINT `fk_Transaction_Product1`
    FOREIGN KEY (`Product_ProductID`)
    REFERENCES `Wicked_Candles`.`Product` (`ProductID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Wicked_Candles`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Wicked_Candles`.`User` (
  `UserID` INT NOT NULL,
  `Name` VARCHAR(100) NOT NULL,
  `PhoneNumber` INT NULL,
  `Email_Address` VARCHAR(100) NOT NULL,
  `Street` VARCHAR(100) NULL,
  `State` VARCHAR(45) NULL,
  `Zip` INT NULL,
  `City` VARCHAR(45) NULL,
  `CC_CCID` INT NOT NULL,
  `Cart_CartID` INT NOT NULL,
  `WishList_WishListID` INT NOT NULL,
  `Transaction_TransactionID` INT NOT NULL,
  PRIMARY KEY (`UserID`, `CC_CCID`, `Cart_CartID`, `WishList_WishListID`, `Transaction_TransactionID`),
  INDEX `fk_User_CC_idx` (`CC_CCID` ASC),
  INDEX `fk_User_Cart1_idx` (`Cart_CartID` ASC),
  INDEX `fk_User_WishList1_idx` (`WishList_WishListID` ASC),
  INDEX `fk_User_Transaction1_idx` (`Transaction_TransactionID` ASC),
  CONSTRAINT `fk_User_CC`
    FOREIGN KEY (`CC_CCID`)
    REFERENCES `Wicked_Candles`.`CC` (`CCID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Cart1`
    FOREIGN KEY (`Cart_CartID`)
    REFERENCES `Wicked_Candles`.`Cart` (`CartID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_WishList1`
    FOREIGN KEY (`WishList_WishListID`)
    REFERENCES `Wicked_Candles`.`WishList` (`WishListID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_Transaction1`
    FOREIGN KEY (`Transaction_TransactionID`)
    REFERENCES `Wicked_Candles`.`Transaction` (`TransactionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
